test the release

diff --git a/build-bin/maven/maven_release b/build-bin/maven/maven_release
--- a/build-bin/maven/maven_release
+++ b/build-bin/maven/maven_release
@@ -15,6 +15,7 @@
 
 set -ue
 
+# This script creates a git `N.M.L` version tag which later will have `deploy` run against it.
 # This script creates a git `MAJOR.MINOR.PATCH` version tag which later will have `deploy` run against it.
 #
 # In CI..
@@ -25,23 +26,21 @@ export MAVEN_OPTS="$($(dirname "$0")/maven_opts)"
 
 trigger_tag=${1?trigger_tag is required. Ex release-1.2.3}
 release_version=$(build-bin/git/version_from_trigger_tag release- ${trigger_tag})
+release_branch=${2:-master}
 
-# Checkout the branch that triggered this build
-git fetch origin
-commit_sha=$(git rev-parse "$trigger_tag")
-echo "current sha: $commit_sha"
-branches=$(git branch --contains "$commit_sha")
-echo "branches: $branches"
-branch_name=$(echo "$branches" | head -n 1 | awk '{print $2}')
-echo "current branch: branch_name"
-if [ -z "$branch_name" ]; then
-  default_branch="master"
-  echo "Unable to determine a valid branch. Auto-selecting the default branch: $default_branch"
-  branch_name=$default_branch
+# Checkout master, as we release from master, not a tag ref
+git fetch --no-tags --prune --depth=1 origin +refs/heads/${release_branch}:refs/remotes/origin/${release_branch}
+git checkout ${release_branch}
+
+# Ensure no one pushed commits since this release tag as it would fail later commands
+commit_local_release_branch=$(git show --pretty='format:%H' ${release_branch})
+commit_remote_release_branch=$(git show --pretty='format:%H' origin/${release_branch})
+if [ "$commit_local_release_branch" != "$commit_remote_release_branch" ]; then
+  >&2 echo "${release_branch} on remote 'origin' has commits since the version to release, aborting"
+  exit 1
 fi
-echo "Ready to checkout branch $branch_name"
-git checkout "$branch_name"
 
 git submodule update --init --recursive
 # Prepare and push release commits and the version tag (N.N.N), which triggers deployment.
 ./mvnw --batch-mode -nsu -DreleaseVersion=${release_version} -Denforcer.fail=false -Darguments="-DskipTests -Dcheckstyle.skip=true -Denforcer.fail=false" release:prepare
+
